name: Workflow

on:
  push:
    branches:
      - main
    paths:
      - "package.json"

jobs:
  check-version:
    name: Package
    uses: ./.github/workflows/check-version.yml

  build:
    name: Package
    needs:
      - check-version
    if: needs.check-version.outputs.is-changed == 'true'
    uses: ./.github/workflows/build.yml
    with:
      node-version: "22.x"
      package-version: ${{ needs.check-version.outputs.version }}

  deploy-npm:
    name: Package
    needs:
      - check-version
      - build
    uses: ./.github/workflows/deploy-npm.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    with:
      node-version: "22.x"
      package-version: ${{ needs.check-version.outputs.version }}

  deploy-github:
    name: Package
    needs:
      - check-version
      - build
    uses: ./.github/workflows/deploy-github.yml
    with:
      node-version: "22.x"
      package-version: ${{ needs.check-version.outputs.version }}
